package com.qxtao.easydict.adapter.dict

const val TYPE_BLNG_CLASSIFICATION_SELECT = -1001
const val TYPE_BLNG_CLASSIFICATION_NORMAL = -1000

const val TYPE_THEASAURUS_HEADER = -1002
const val TYPE_THEASAURUS_NORMAL = -1003